import Head from 'next/head'
import Posts from '../components/Posts'

export default function Home() {
  return (
    <div className="w-1/2">
      <Head>
        <title>GoBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Posts />

    </div>
  )
}
